2020-22-22 15:14:27 test_re.py[line:28] INFO get 请求出错，出错原因: Expecting value: line 1 column 1 (char 0)
2020-22-22 15:15:32 test_re.py[line:28] INFO get 请求出错，出错原因: Expecting value: line 1 column 1 (char 0)
2020-22-22 15:25:07 test_re.py[line:29] INFO get 请求出错，出错原因: string indices must be integers
2020-22-22 15:27:00 test_re.py[line:29] INFO get 请求出错，出错原因: string indices must be integers
2020-22-22 15:37:55 test_re.py[line:28] INFO get 请求出错，出错原因: HTTPConnectionPool(host='wthrcdn.etouch.cn', port=80): Max retries exceeded with url: /weather_mini?city=%E5%8C%97%E4%BA%AC (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000131294D2308>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-22-22 15:38:06 test_re.py[line:28] INFO get 请求出错，出错原因: HTTPConnectionPool(host='wthrcdn.etouch.cn', port=80): Max retries exceeded with url: /weather_mini?city=%E5%8C%97%E4%BA%AC (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021A36F42248>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-22-22 15:38:17 test_re.py[line:28] INFO get 请求出错，出错原因: HTTPConnectionPool(host='wthrcdn.etouch.cn', port=80): Max retries exceeded with url: /weather_mini?city=%E5%8C%97%E4%BA%AC (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FBEF659C08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-22-22 15:39:53 test_re.py[line:40] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:41:49 test_re.py[line:40] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:42:06 test_re.py[line:40] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:43:43 test_re.py[line:40] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:44:22 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:44:56 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:45:32 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:46:06 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:48:37 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:48:46 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:51:08 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:52:32 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:53:16 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:53:27 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:54:24 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:54:37 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 15:54:48 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:00:55 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:01:14 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:02:13 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:02:20 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:16:19 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:17:12 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:18:09 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:19:12 test_re.py[line:41] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:32:51 test_re.py[line:42] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:41:49 test_re.py[line:42] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
2020-22-22 16:42:46 test_re.py[line:42] INFO post请求出错，出错原因:Expecting value: line 1 column 1 (char 0)
